### ISSUE TITLE
Python 3: Layout problem for circular convolution

### ISSUE THREAD

**Issue by mundya** [nengo/nengo_gui#371] opened 2015-06-09 16:08 UTC
![product_missing](https://cloud.githubusercontent.com/assets/3439837/8062815/d973cc10-0e9f-11e5-840d-932059d9e38f.png)

The internals of the product network don't show up.  When I click to expand the product network this appears in the console:

```
(process:6692): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
Traceback (most recent call last):
  File "/home/andrew/Documents/University/rig_devel/nengo_gui/nengo_gui/swi.py", line 237, in handle_ws_request
    getattr(self, command)(*[client] + args[1:], **db)
  File "/home/andrew/Documents/University/rig_devel/nengo_gui/nengo_gui/server.py", line 147, in ws_viz_component
    component.update_client(client)
  File "/home/andrew/Documents/University/rig_devel/nengo_gui/nengo_gui/components/netgraph.py", line 243, in update_client
    self.expand_network(network, client)
  File "/home/andrew/Documents/University/rig_devel/nengo_gui/nengo_gui/components/netgraph.py", line 334, in expand_network
    pos = self.layout.make_layout(network)
  File "/home/andrew/Documents/University/rig_devel/nengo_gui/nengo_gui/layout.py", line 130, in make_layout
    layout.draw(3)  # do three passes to improve crossings
  File "/home/andrew/Documents/University/rig_devel/nengo_gui/nengo_gui/grandalf/layouts.py", line 329, in draw
    for (l,mvmt) in self.ordering_step():
  File "/home/andrew/Documents/University/rig_devel/nengo_gui/nengo_gui/grandalf/layouts.py", line 477, in ordering_step
    mvmt = l.order()
  File "/home/andrew/Documents/University/rig_devel/nengo_gui/nengo_gui/grandalf/layouts.py", line 150, in order
    self.sort(cmp=(lambda x,y: cmp(sug.grx[x].bar,sug.grx[y].bar)))
TypeError: 'cmp' is an invalid keyword argument for this function
```

This works for @xchoo in Python 2 I believe.

**Comment by tbekolay** [comment] 2015-06-09 16:11
Oh snap! Yeah, they changed `sort` and `sorted` in Python 3. See [this possible guide to upgrading](https://docs.python.org/3.3/howto/sorting.html#the-old-way-using-the-cmp-parameter). This is part of `grandalf` and not our code, but yeah, if we're using it we'll need to fix this.

**Comment by tbekolay** [comment] 2015-06-09 20:36
This actually works for me on Python 3.4.3. Are you sure that you have the most recent version of master @mundya? I can see a bug in your screenshot that should be fixed now. Have you updated your `git remote` to `https://github.com/nengo/nengo_gui.git` ?

**Comment by mundya** [comment] 2015-06-09 21:10
`remote` is definitely correct.  I was accidentally sat on the Python 3 fix branch from earlier. Master looks like this for me now.

![product_missing2](https://cloud.githubusercontent.com/assets/3439837/8069688/42222692-0eca-11e5-96c4-3de294bb0026.png)

Not sure that's different from above? What should I be looking for?

**Comment by tbekolay** [comment] 2015-06-09 21:13
Weird... I definitely thought we fixed the bug where you'd get `./././././my/path`. That should be looked at again. If you do an auto-layout, do you get any exceptions in the console? What version of Python 3 are you using?

**Comment by tcstewar** [comment] 2015-06-09 23:17
> I definitely thought we fixed the bug where you'd get ./././././my/path

We have fixed that.  the screenshot shows ```../../../../../../tmp/whatever```, which is the correct relative path from where nengo_gui was started.

**Comment by tbekolay** [comment] 2015-06-10 12:31
> the screenshot shows `../../../../../../tmp/whatever`

Haha... my old man eyes fail me again.

And I was able to reproduce this error in Python 3... For some reason my virtualenv was just like... half activated? I dunno, there was a weird path thing. In any case, I'll try to fix this up.

**Comment by tbekolay** [comment] 2015-06-10 13:17
This should be fixed now thanks to #378. @mundya can you test this out? It's in master now, so you can just test in master...

**Comment by mundya** [comment] 2015-06-10 13:28
@tbekolay Works for me, thanks!

**Comment by tbekolay** [comment] 2015-06-10 13:30
phew! Sigh of relief breathed.

**Closed by tbekolay** 2015-06-10 13:30 UTC
