### ISSUE TITLE
Can't configure 'pos'

### ISSUE THREAD

**Issue by tbekolay** [nengo/nengo_gui#627] opened 2015-12-10 15:44 UTC
Can provide more detail later, but just wanted to check and see if this is a known issue with a workaround...

When trying to open up a model (that has some SPA networks in it) I get the following error from the config system:

```python
AttributeError: Cannot configure the built-in parameter 'pos' on an instance of 'SPA'. Please set the attribute directly on the object.
```

Is this because I'm adding a `SPA` instance to a `Network`? Does the top level network have to be a `SPA` instance too?

**Comment by tcstewar** [comment] 2015-12-10 15:46
Hmm..  could be...  I don't think I'd ever considered putting a SPA inside a Network.  But that should be a reasonable thing to do and if that's what's causing the error that's a bug.

**Comment by tbekolay** [comment] 2015-12-10 19:54
Ahhh I figured out what's happening. I have a working memory representing the current position in the list, so I called it `pos`. When the config system goes to associate `pos` with the network that owns that working memory, it has an attribute called `pos` so the config system doesn't like it (because you should be doing `whatever.pos` not `config[whatever].pos`)

I don't think I'll be the last one to call a network `pos`, so I'd recommend we change the name of that parameter. Maybe `_pos`? `__pos`? `ngpos`? Something that someone is unlikely to give as an actual attribute name...

**Comment by bjkomer** [comment] 2016-02-06 21:05
duplicate of #562

An underscore in front seems like a reasonable way to fix this.

**Comment by Seanny123** [comment] 2016-06-06 18:19
As Brent indicated, this is a duplicate, so I'm closing this issue.

**Closed by Seanny123** 2016-06-06 18:19 UTC
