### ISSUE TITLE
Slider doesn't disappear after the nengo.Node was deleted

### ISSUE THREAD

**Issue by ricardodeazambuja** [nengo/nengo_gui#759] opened 2016-06-07 16:25 UTC

**Comment by Seanny123** [comment] 2016-06-07 18:28
This doesn't happen to me on the `master` branch using Linux. What OS and browser are you running? What steps can be used to reproduce the issue?

**Comment by Seanny123** [comment] 2017-12-28 18:03
I still can't reproduce it using Firefox and Windows, so I'm going to close this issue. However, feel free to re-open it if you find this bug again!

**Closed by Seanny123** 2017-12-28 18:03 UTC
