### ISSUE TITLE
Should be able to load pickled networks into GUI

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_gui#819] opened 2016-09-01 00:34 UTC
Sometimes I build complicated networks that require running multiple simulator to get decoders. Pickling them (using the Nengo `copy` branch) and then opening them in the GUI would be nice. At the moment, when I try to accomplish this with the following code:

```
import nengo
import cPickle as pickle


with open("model", "r") as ff:
    model = pickle.load(ff)
```

Where the model network was previously created by running:

```
import nengo
import cPickle as pickle

with nengo.Network() as model:
    out_nd = nengo.Node(size_in=1)

    osc = nengo.networks.Oscillator(0.1, 1, 300)


    nengo.Connection(osc.ensemble[0], out_nd)

with open("model", "w") as ff:
    pickle.dump(model, ff)
```

I get the following error:

```
Traceback (most recent call last):
  File "/home/saubin/git/nengo_gui/nengo_gui/server.py", line 235, in do_GET
    self.http_GET()
  File "/home/saubin/git/nengo_gui/nengo_gui/server.py", line 251, in http_GET
    response = getattr(self, command)()
  File "/home/saubin/git/nengo_gui/nengo_gui/guibackend.py", line 92, in auth_checked
    return fn(inst)
  File "/home/saubin/git/nengo_gui/nengo_gui/guibackend.py", line 199, in serve_main
    components = page.create_javascript()
  File "/home/saubin/git/nengo_gui/nengo_gui/page.py", line 333, in create_javascript
    component_js = '\n'.join([c.javascript() for c in self.components])
  File "/home/saubin/git/nengo_gui/nengo_gui/components/sim_control.py", line 185, in javascript
    js = self.javascript_config(info)
  File "/home/saubin/git/nengo_gui/nengo_gui/components/component.py", line 92, in javascript_config
    for attr in self.config._clsparams.params:
TypeError: 'instancemethod' object is not iterable
```

I tried to work around it, by starting the Nengo GUI in the file:

```
import nengo
import nengo_gui
import cPickle as pickle


with open("model", "r") as ff:
    model = pickle.load(ff)

nengo_gui.GUI(filename="pickle_test.py", model=model).start()
```

But I got the same error.

**Comment by Seanny123** [comment] 2016-09-01 00:49
Upon further review, this might just be an issue with the `copy` branch of Nengo, since I get the above error even when trying to run the `nengo` command.

**Comment by jgosmann** [comment] 2016-09-01 03:05
Due to some changes to the parameter system API in th `copy` branch changes to nengo_gui are necessary. The line `for attr in self.config._clsparams.params:` raising the error has to be changed to `for attr in self.config._clsparams.params():` I believe. There might be more changes necessary.

**Comment by jgosmann** [comment] 2016-09-21 20:52
I updated the nengo/nengo#984 PR, do you care to test if the issue is fixed with that?

**Comment by Seanny123** [comment] 2016-09-21 23:30
This doesn't fix the bug for me.

**Comment by jgosmann** [comment] 2016-10-03 18:49
With Python 3 it works for me (when adjusting the `import` and `open` statements accordingly). I don't see any reason why it shouldn't work with Python 2.

**Comment by tbekolay** [comment] 2016-11-03 19:31
The snippets in the original post work for me with the current version of https://github.com/nengo/nengo/pull/984.

**Comment by Seanny123** [comment] 2016-11-04 08:38
Works for me now, so close this once the branch is merged.

**Closed** 2016-11-04 14:22 UTC
Labels: bug, feature request
