### ISSUE TITLE
Cannot "Configure Settings" in IPythonViz

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_gui#938] opened 2017-11-25 19:54 UTC
In an IPythonViz simulation, you cannot click "Configure Settings". Nothing happens and the console prints the error:

```
top_toolbar.js:86 Uncaught TypeError: Cannot read property 'auto_update' of undefined
    at Object.Nengo.Toolbar.config_modal_show (top_toolbar.js:86)
    at eval (eval at Nengo.SimControl.on_message (sim_control.js:117), <anonymous>:1:25)
    at Nengo.SimControl.on_message (sim_control.js:117)
    at WebSocket.ws.onmessage (sim_control.js:38)
```

Also, if the screen is too small, you literally can't see "Configure Settings" if the windows is too small.

**Comment by jgosmann** [comment] 2017-11-26 00:33
Duplicate of #910 (which has already a patch).

**Closed by jgosmann** 2017-11-26 00:33 UTC
Labels: bug
