### ISSUE TITLE
Semantic pointer cloud stops updating

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo_gui#636] opened 2016-01-13 20:11 UTC
This happens for me with a lot of semantic pointers when I try to zoom. The following exception is printed to the console:

```
Traceback (most recent call last):
  File "/Volumes/Home/blubb/Documents/projects/uni/nengo_gui/nengo_gui/server.py", line 142, in ws_viz_component
    component.update_client(client)
  File "/Volumes/Home/blubb/Documents/projects/uni/nengo_gui/nengo_gui/components/pointer.py", line 84, in update_client
    client.write(data, binary=False)
  File "/Volumes/Home/blubb/Documents/projects/uni/nengo_gui/nengo_gui/swi.py", line 695, in write
    self._sendall(header)
  File "/Volumes/Home/blubb/Documents/projects/uni/nengo_gui/nengo_gui/swi.py", line 722, in _sendall
    bytes_sent += self.socket.send(data[bytes_sent:])
error: [Errno 35] Resource temporarily unavailable
Traceback (most recent call last):
  File "/Volumes/Home/blubb/Documents/projects/uni/nengo_gui/nengo_gui/server.py", line 142, in ws_viz_component
    component.update_client(client)
  File "/Volumes/Home/blubb/Documents/projects/uni/nengo_gui/nengo_gui/components/pointer.py", line 84, in update_client
    client.write(data, binary=False)
  File "/Volumes/Home/blubb/Documents/projects/uni/nengo_gui/nengo_gui/swi.py", line 695, in write
    self._sendall(header)
  File "/Volumes/Home/blubb/Documents/projects/uni/nengo_gui/nengo_gui/swi.py", line 722, in _sendall
    bytes_sent += self.socket.send(data[bytes_sent:])
error: [Errno 35] Resource temporarily unavailable
```

**Comment by Seanny123** [comment] 2016-02-05 19:09
Although we could hypothetically just catch this error, I just thought I would note that I coudn't reproduce this on Ubuntu and Chrome. Jan, what OS and browser were you using when you saw this error?

**Comment by jgosmann** [comment] 2016-02-05 19:21
Might have been OS X.

**Comment by jgosmann** [comment] 2016-02-05 19:49
Browser either Firefox or Chrome.
I think, to reproduce it, you'll need a vocabulary large enough. Try like 5000 elements.

**Comment by Seanny123** [comment] 2016-02-06 17:30
Jan couldn't reproduce, so closing.

**Closed by Seanny123** 2016-02-06 17:30 UTC
Labels: bug
