### ISSUE TITLE
Addition Bug?

### ISSUE THREAD

**Issue by samtriolo** [nengo/nengo_gui#463] opened 2015-07-06 04:58 UTC
I'm an amateur hobbyist playing around with this stuff.  I tried editing the values in the built-in / basic "addition.py" to increase the sum / output (value of ensemble C) two different ways, and both times the sum / output was significantly less.  

For example, total input (3 inputs / ensembles) of 1.4 displayed only an output value (ensemble C) of approximately 1.1.  Total input (2 inputs) of 1.2 displayed only an output value of approximately 1.05.

It seems unlikely that something so basic is not working correctly, I'm assuming I either made a simple mistake somewhere and / or there's some deeper CompNeuro reason why it is behaving this way, but thought I would say something just in case.

Two separate approaches:
1) I tried increasing the values in the "addition.py" file to "0.5" and "0.7" so that the sum would be 1.2 (code changes involves using built-in example "addition.py" and editing the values of the input nodes to "0.5" and "0.7" on lines 18 and 19; no other changes)

2) I tried creating a third ensemble / input ("d"), in the "addition.py" file.  All three inputs (0.5, 0.3, 0.6) would sum to 1.4.  (code below)

Nengo GUI 2.0 on Ubuntu, running via firefox.

import nengo
model = nengo.Network()
with model:
    # Create 3 ensembles each containing 100 leaky integrate-and-fire neurons
    a = nengo.Ensemble(n_neurons=100, dimensions=1)
    b = nengo.Ensemble(n_neurons=100, dimensions=1)
    c = nengo.Ensemble(n_neurons=100, dimensions=1)
    d = nengo.Ensemble(n_neurons=100, dimensions=1)

    # Create input nodes representing constant values
    stim_a = nengo.Node(0.5)
    stim_b = nengo.Node(0.3)
    stim_d = nengo.Node(0.6)

    # Connect the input nodes to the appropriate ensembles
    nengo.Connection(stim_a, a)
    nengo.Connection(stim_b, b)
    nengo.Connection(stim_d, d)

    # Connect input ensembles a and b to output ensemble c
    nengo.Connection(a, c)
    nengo.Connection(b, c)
    nengo.Connection(d, c)

![addition2inputs](https://cloud.githubusercontent.com/assets/13193861/8515914/2eb4483e-2369-11e5-93f4-b96dc4609735.jpg)
![addition3inputs](https://cloud.githubusercontent.com/assets/13193861/8515916/330e73c8-2369-11e5-994b-d1cfbb7e7afa.jpg)

**Comment by tcstewar** [comment] 2015-07-06 05:15
Hi @samtriolo , and thanks for taking a look at nengo!

What you're seeing there is actually expected behaviour.  There's a parameter on the ```Ensemble``` that lets you specify its ```radius```; that is, the range of values over which it should be optimized for representation.  Since neurons have physical limitations (like their maximum rate of firing), there's always going to be some limit to their representational capacity.  So, if you want the neurons to represent values between -100 and 100, you set the radius to 100.  If you want them to be in the range -0.0001 to 0.0001, then set the radius to 0.0001.  We call this a radius because when you extend up to higher dimensions, the neurons are good at representing inside a sphere of that radius (rather than a box).

So, in your particular example, if you set Ensemble ```c``` to have a radius of 1.5 (or 3, or whatever you want), then it should add as expected, as long as the result is inside that radius.

**Comment by Seanny123** [comment] 2015-07-06 11:54
As @tcstewar mentioned, this is an intended effect of computing with neurons. If you want more details on why and how computing with neurons works, you could work through the [Nengo examples](https://pythonhosted.org/nengo/examples.html) in our documentation or read through [course notes](http://compneuro.uwaterloo.ca/research/syde-750.html) on the matter. Hope that helps!

**Comment by jgosmann** [comment] 2015-07-06 14:58
Maybe we have to highlight the effect of the radius more somewhere in the documenation/tutorials? @samtriolo is not the first one overlooking this.

**Comment by Seanny123** [comment] 2015-07-06 17:59
The problem is that it doesn't fit neatly into the examples, nor into the
NEF introduction... Where were you thinking of putting it?

**Comment by s72sue** [comment] 2015-07-06 18:16
I think it makes sense to illustrate the effect of radius at least in the
addition example. I think in the HBB book, Chris has mentioned this effect
and so I have included it in the updated tutorials for nengo 2 (
https://github.com/s72sue/Nengo2-Tutorials/blob/master/chapter3/addition.ipynb
).

The example that we have in the documentation uses inputs of less than 1
and since the default radius in nengo is 1, so the effect of radius gets
hidden and isn't clear from the example.

-Sue

**Comment by samtriolo** [comment] 2015-07-07 03:30
Thanks to all who contribute to Nengo - it makes a difference.  I am very interested in CompNeuro, but I don't have background in the core topics, with the exception of some Comp Sci.  Having something I can easily build models with to understand the lower-level Math and other concepts helps a lot.

@tcstewar - thank you for the clarification, I will look into that more.

@Seanny123 - thank you for the suggestion.  I was still working on adapting the tutorials in 1.4 language to 2.0.  I had not however, seen those course notes; I will check them out.

@s72sue - I hadn't seen this tutorial before (perhaps for a reason - a cursory glance at the empty readme :-) seems to imply "under construction"). If you'd like some feedback after a draft is ready, and I am capable of getting through some of the material, I'd be happy to help.

**Comment by s72sue** [comment] 2015-07-07 05:00
Hi @samtriolo <https://github.com/samtriolo>, these tutorials are meant to
complement the How to build a Brain book (not sure whether you are already
going through it or plan to). The book has all the tutorials based on
nengo1.4 and these new tutorials which I have been working on are a
translation to nengo2. Though I still need to work on one or two of the
models, most of them are done so you are most welcome to use them and some
feedback would be great! Let me know if you have any questions.

Cheers,
Sue

**Comment by samtriolo** [comment] 2015-07-08 05:04
@s72sue - 

I had looked at it briefly some time ago.  I bounce between a number of Neuro / Math / CompNeuro resources trying to stitch it all together.  I was currently going through Neural Engineering, but I'll go back to the Build Brain book this weekend.  I will put together some feedback as I go through it, thanks for your reply.

Sam

**Comment by s72sue** [comment] 2015-07-08 13:47
Sounds good. Thanks!

**Comment by Seanny123** [comment] 2016-06-06 18:58
Hey @samtriolo, do you have any more questions? May we close this issue? (:

**Comment by samtriolo** [comment] 2016-06-09 23:21
Go ahead and close. Thanks for asking.

**Closed** 2016-06-09 23:22 UTC
