### ISSUE TITLE
Adjust the filter used on Value plots

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo_gui#462] opened 2015-07-05 19:51 UTC
As per discussion in #461, an option on the right-click menu to adjust the filter used would be handy.

**Comment by Seanny123** [comment] 2015-10-17 19:18
Duplicate of #399

**Comment by studywolf** [comment] 2015-10-27 20:20
+1

**Comment by Seanny123** [comment] 2016-06-06 18:59
Resolved by #751

**Closed by Seanny123** 2016-06-06 18:59 UTC
