### ISSUE TITLE
Pause button disappears

### ISSUE THREAD

**Issue by celiasmith** [nengo/nengo_gui#334] opened 2015-06-05 14:06 UTC
When I run this model, the pause button isn't there.
```
import nengo
import numpy as np

model = nengo.Network('Heart Oscillator', seed=1)

tau = 0.01
r=4

def feedback(x):    
    return [-tau*r*x[1]+1.02*x[0], tau*r*x[0]+1.02*x[1]]

def heart_shape(x):
    theta = np.arctan2(x[1], x[0])
    r = 2 - 2 * np.sin(theta) + np.sin(theta)*np.sqrt(np.abs(np.cos(theta)))/(np.sin(theta)+1.4)
    return -r*np.cos(theta), r*np.sin(theta)

with model:
    stim = nengo.Node(lambda t: [.5,.5] if t<.02 else [0,0])
    
    heart_osc = nengo.Ensemble(1000, dimensions=2)
    heart = nengo.Ensemble(100, dimensions=2, radius=4)
    
    nengo.Connection(stim, heart_osc)
    nengo.Connection(heart_osc, heart_osc, function=feedback, synapse=tau)
    nengo.Connection(heart_osc, heart, function=heart_shape, synapse=tau)
    
    heart_p = nengo.Probe(heart, synapse=tau)
```

**Comment by celiasmith** [comment] 2015-06-05 14:09
I think this is fixed by #312 ...

**Comment by tbekolay** [comment] 2015-06-08 13:37
For me, this seems to happen the first time I press the play button. After that, I can press it and it'll go back to play, and the next time I push it, it'll go to the pause button. But after that first press, it will be blank.

**Comment by tcstewar** [comment] 2015-06-08 13:42
I see this now and then as well, but if I click on the text editor it comes back.

**Comment by Seanny123** [comment] 2015-08-12 15:47
This is still present on the master branch, btw.

**Comment by pblouw** [comment] 2016-02-05 20:41
I am unable to reproduce this bug on master, so it seems that some change between now and last August has fixed it.

**Comment by tcstewar** [comment] 2016-02-05 21:35
I think it's always been pretty random....  Maybe it's fixed, but If anyone runs into this again and can find a way to replicate it, that'd be great....

**Comment by tcstewar** [comment] 2016-03-31 17:24
I haven't seen this bug in a while, so hopefully it's been magically fixed....  I'll close this and see if it crops up again.

**Closed by tcstewar** 2016-03-31 17:24 UTC
Labels: bug
