### ISSUE TITLE
Refactor nengo_gui.gui.GUI ?

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo_gui#554] opened 2015-09-11 21:53 UTC
While creating the flow documents for the presentation I'm making in September, I noticed some weird code-flow in `nengo_gui.gui.GUI`.

Basically, this is what I understand of the start-up so far:
- main.py parses arguments and starts instance of nengo_gui.gui.GUI
- GUI starts nengo_gui.server.Server which inherits from SWI
- SWI then calls various server functions (`prepare_server` and `begin_lifecycle`) from GUI

Why does `nengo_gui.gui.GUI` need to act as a wrapper around the methods `prepare_server` and `begin_lifecycle`? Should this be refactored to eliminate the circular-like function calls? I understand that these calls are also made by the iPython startup, but it's not like the `server` attribute of the `GUI` is private.

**Comment by tcstewar** [comment] 2015-09-12 08:51
I totally agree...  indeed, I think this is a duplicate of #456

**Comment by jgosmann** [comment] 2017-05-01 18:52
Resolved in #673.

**Closed by jgosmann** 2017-05-01 18:52 UTC
Labels: enhancement
