### ISSUE TITLE
Choose which semantic pointers/pairs to display on a semantic pointer plot

### ISSUE THREAD

**Issue by bjkomer** [nengo/nengo_gui#892] opened 2017-05-16 20:52 UTC
It would be nice if there is a way to configure the semantic pointer plots to only display a subset of the similarities. This could be through a right-click menu on the plot, and/or in the code editor somehow.

Currently if you do a 'show pairs' on a semantic pointer plot lots of combinations can come up, but you may only care about a few of them and the rest just make the plot harder to read.

This seems like it would be related to #60

**Comment by jgosmann** [comment] 2017-05-17 02:56
Commonly requested feature, but apparently no one needs it badly enough to go along and implement it. Closing this as a duplicate of #602. Feel free to reopen if you think this issue request something not covered by #602.

**Closed by jgosmann** 2017-05-17 02:56 UTC
Labels: feature request

**Comment by tbekolay** [comment] 2017-05-17 03:24
> Commonly requested feature, but apparently no one needs it badly enough to go along and implement it.

Generally speaking, not everyone that wants a particular feature is going to have the time, patience, ability, or altruism to implement it. I think it's still a useful thing for anyone to note when they want a particular feature (whether as a new issue or by adding a comment to an old issue) in order to help us realize what our users want and prioritize our time accordingly. Thanks for the feature request Brent; FYI this should hopefully be a much easier feature to implement post-refactoring, though there will have to be some thought given to exactly how one specifies the pointers to be displayed.
