### ISSUE TITLE
Drop-down menu causes nengo_gui to crash

### ISSUE THREAD

**Issue by MichaelOVertolli** [nengo/nengo_gui#687] opened 2016-02-26 21:03 UTC
This is a strange glitch that is probably very low priority, but it happened so I'll report it.

First, I'm using nengo_gui 0.2.0-dev and I have not tested this problem in the stable version.

Problem:
When the drop-down menu for opening files is open and the user clicks in the bottom-right hand corner (it's a small white box between the two scroll bars), holds the click until both scroll bars start scrolling, then drags the cursor (still holding the click) outside of the drop-down window the server crashes.

I can't seem to reproduce this error by clicking and holding anywhere else in the drop-down menu nor if I quickly drag the cursor out of the menu.

**Comment by Seanny123** [comment] 2016-02-26 22:08
Reproduced on master. This is an amazing bug! Thanks for pointing it out. Not sure what's causing it, but we will investigate.

**Comment by jgosmann** [comment] 2016-02-26 22:20
Can't reproduce on Firefox.
Can reproduce on Chromium, but not if I open two tabs connecting to the GUI.

**Comment by jgosmann** [comment] 2016-02-26 22:25
Can't reliably reproduce after opening the developer console.

This bug is weird :confounded:

**Comment by Seanny123** [comment] 2016-06-06 18:28
Resolved in #746 by eliminating the drop-down menu entirely.

**Closed by Seanny123** 2016-06-06 18:28 UTC
Labels: bug
