### ISSUE TITLE
Plots (value and spike) look blank after first few seconds of simulation.

### ISSUE THREAD

**Issue by s72sue** [nengo/nengo_gui#490] opened 2015-07-16 20:16 UTC
When simulating the following example, the value and spike plots look blank after first few seconds of simulation. However on hitting the pause button, the spikes/value plot shows up. On draging back in time, the spikes/value plot can be seen, however on hitting play, they again disappear.  

This doesn't happen when the number of neurons is over 500.

![test](https://cloud.githubusercontent.com/assets/12284191/8733503/20cef888-2bd2-11e5-91e4-217f5b4cc0e1.png)

**Comment by tcstewar** [comment] 2015-07-16 20:41
This is a duplicate of #357

**Comment by cchan987** [comment] 2015-07-17 18:42
^

**Closed by cchan987** 2015-07-17 18:42 UTC
Labels: bug
