### ISSUE TITLE
Ensembles become larger on first resize movment

### ISSUE THREAD

**Issue by cchan987** [nengo/nengo_gui#422] opened 2015-06-15 19:05 UTC
When resizing an ensemble by dragging an edge, after the first mouse movement the ensemble pops to being a larger size.

**Comment by jgosmann** [comment] 2015-06-15 20:01
Yeah, I noticed that too. Someone must have screwed up the resize code again.

**Comment by tbekolay** [comment] 2015-06-15 20:05
I was playing around trying to reproduce this and I noticed that this only seems to happen when dragging from the bottom edge. Dragging from the top edge makes the ensemble become super small. There's something weird about where we think the y-position of the cursor is? I think?

**Comment by jgosmann** [comment] 2015-06-16 14:04
Part of it was broken by me by changing the position of the main div to be relative to the top toolbar.
Part of it was probably choosing the wrong change in a rebase. [In this commit](https://github.com/nengo/nengo_gui/commit/28fdabf#diff-b0d3269aa66b233b3e461420240226cbL168) the factor of 2 disappears, but it shouldn't.

**Comment by tbekolay** [comment] 2015-06-16 16:07
This is only partially fixed by #429, so reopening. See below video for current issues.

[![vidya](http://img.youtube.com/vi/fQL7QwSvk1Y/0.jpg)](http://www.youtube.com/watch?v=fQL7QwSvk1Y "Resize issues")

**Comment by jgosmann** [comment] 2015-06-18 16:11
The width of the items is indeed of because the width of the main netgraph area is wrong. That is mainly for two reasons:

1. We calculate the width on our own. I think, **whenever possible we should leave size calculations to the browser and position elements relative to the relevant elements**. It is less error prone especially when parts of the layout change and probably also faster.
2. The editor is just appended at the end of the body. This is not related to the structure of the layout at all and makes it of course impossible to adhere to point 1. **We should keep a logical structure in the HTML.** For the editor it means that it should be put into the `vmiddle` div.

**Comment by jgosmann** [comment] 2015-06-18 16:31
Also rule of thumb: It should seldom be necessary to use  `position: fixed`.

**Closed** 2015-07-13 21:16 UTC
Labels: bug
